name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main  # Adjust this as necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Adjust this as necessary

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Build
      run: npm run build

    - name: Zip build directory
      run: zip -r build.zip build/

    # Future backend and MongoDB steps would go here
    # Placeholder for backend setup
    # Placeholder for MongoDB setup

    - name: Deploy to AWS Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v18
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: ${{ secrets.AWS_REGION }}
        application_name: ${{ secrets.APPLICATION_NAME }}
        environment_name: ${{ secrets.ENVIRONMENT_NAME }}
        version_label: ${{ github.sha }}
        deployment_package: build.zip
